---
name: "Project Milestone Issue"
description: "Template for tracking project milestones."
labels: [milestone, tracking]
assignees: []
---

# GitHub Issue Template: Project Milestone Tracking

## **Project Milestone Issue Template**

**Title:** `[Your Name] – [Milestone Name]`

---

## **Milestone Details**
- **Milestone Name:** [Enter milestone name]
- **Week:** [Enter the corresponding week number]
- **Due Date:** [Enter due date]
- **Description:** [Provide a brief description of what this milestone entails]
- **Deliverables:**
  - [List all required deliverables for this milestone]
- **Status:** `[ ] Not Started` `[ ] In Progress` `[ ] Completed`

---

## **Tasks & Subtasks**
- [ ] Task 1: [Describe task]
- [ ] Task 2: [Describe task]
- [ ] Task 3: [Describe task]

---

## **Precedent Research & Resources**
- [Include relevant precedent research, articles, links, or sources]
- [Reference any past work that informs this milestone]

---

## **Challenges & Open Questions**
- [Describe any potential challenges or uncertainties related to this milestone]
- [List any questions that require clarification or further exploration]

---

## **Review & Feedback**
- **Peer Review:** [Request feedback from at least one peer]
- **Instructor Comments:** [Leave space for instructor feedback]

---

## **Next Steps**
- [Outline the next steps after completing this milestone]

✅ **Final Check:** Ensure all deliverables are complete before marking this issue as **Completed**.
